name: Tests
on: push
jobs:
  workflows:
    strategy:
      matrix:
        platform: [ubuntu-latest] # mac-os in development
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install modules
        run: npm i
      - name: Build contract
        run: npm run build
      - name: Run tests
        run: npm run test
